version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus/
    networks:
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    pid: host
    restart: unless-stopped
    networks:
      - monitoring_network

  grafana:
    build: .
    image: melvin-grafana
    container_name: grafana
    restart: unless-stopped
    env_file: ".env"
    ports:
      - '3030:3030'
    volumes:
      - 'grafana_storage:/var/lib/grafana'

    networks:
      - monitoring_network

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter
    container_name: dcgm-exporter
    ports:
      - "9400:9400"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_storage: { }
